/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'landing': RouteRecordInfo<'landing', '/', Record<never, never>, Record<never, never>>,
    'auth': RouteRecordInfo<'auth', '/auth/:step', Record<never, never>, Record<never, never>>,
    'feed': RouteRecordInfo<'feed', '/feed', Record<never, never>, Record<never, never>>,
    'profileIntro': RouteRecordInfo<'profileIntro', '/intro/:step', Record<never, never>, Record<never, never>>,
  }
}
